#!/bin/bash
echo "Installing ImageViewer..."
sudo apt-get install git
sudo apt install python3
sudo apt install python3-pip
pip3 install click
pip3 install pygame
Dest_Dir="/usr"
sudo rm -rvf $Dest_Dir/ImageViewer
sudo mkdir -pv $Dest_Dir/ImageViewer
Dest_Dir=$Dest_Dir"/ImageViewer"
sudo chmod a+r $Dest_Dir
sudo chmod a+w $Dest_Dir
cp image_viewer.py $Dest_Dir
chmod a+x $Dest_Dir/*
cd $Home_dir
cat >> .bashrc << "EOF"
alias ImageViewer="python3 /usr/ImageViewer/image_viewer.py"
EOF
source .bashrc
echo "image viewer installed successfully!"
